#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# OnTrak — a local Authentik, and the range pointed at it.
#
# The range's sign-in is Authentik's (docs/operations.md "Sign-in"), and in the
# estate that Authentik is Cerulean's. This script stands up the *local* one —
# deploy/authentik/compose.yaml, its own project, its own database — and then
# wires a range running on this machine to it, so a demo has a real OIDC flow
# behind a real login page without the estate being reachable.
#
#   deploy/authentik/setup.sh              # start Authentik and provision OnTrak
#   deploy/authentik/setup.sh --connect    # ... and point the local portal at it
#   deploy/authentik/setup.sh --down       # stop it (the database is kept)
#
# What it does, in order:
#
#   1. detects this host's address, which is the one address the browser and the
#      portal container can both use for the issuer
#   2. generates deploy/authentik/.env on a first run — Postgres password, the
#      Authentik secret key, the bootstrap admin password and API token, the
#      OIDC client secret, and the seed accounts' password. Never overwrites.
#   3. starts the stack and waits for Authentik to report ready
#   4. runs provision.py, which creates the OnTrak application, its OIDC
#      provider, the groups and the seed accounts through the API
#   5. writes deploy/authentik/ontrak-local.env — the four ONTRAK_PORTAL__OIDC_*
#      values, the instructor group, and the address students are sent to
#
# Why the host address and not `localhost`: the issuer URL has to resolve, and
# give the same answer, for two different clients — the student's browser and the
# portal container. `localhost` is the *container* to the container and the
# Windows host to the browser, and an issuer is not allowed to depend on who is
# asking. The machine's own address is the one name both can reach.
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
ENV_FILE="$HERE/.env"
# The range-facing values: the four ONTRAK_PORTAL__OIDC_* variables, the group
# whose members are instructors, and the address students are sent to. Written
# last on the compose command line so it wins over the checkout's own .env.
LOCAL_ENV_FILE="$HERE/ontrak-local.env"

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m  ✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m  !\033[0m %s\n' "$*"; }
die()  { printf '\033[31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is not installed"
command -v openssl >/dev/null 2>&1 || die "openssl is not installed"


# --------------------------------------------------------------- host address --
# The default-route source is this machine's address on the network that leaves
# the box — the one a browser somewhere else would use. Anything can be forced
# with ONTRAK_LOCAL_HOST (a DNS name, say).
detect_host() {
  if [ -n "${ONTRAK_LOCAL_HOST:-}" ]; then
    printf '%s' "$ONTRAK_LOCAL_HOST"
    return 0
  fi
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null \
      | awk '{ for (i = 1; i < NF; i++) if ($i == "src") { print $(i + 1); exit } }')"
  fi
  printf '%s' "${ip:-127.0.0.1}"
}


# --------------------------------------------------------------------- secrets --
# One generator, so a value is either in .env or it does not exist yet — never a
# second place a secret is decided. Base64 with the shell-hostile characters
# folded out: these values travel through an env file, compose interpolation and
# a URL.
rand() { openssl rand -base64 "$1" | tr -d '\n=' | tr '+/' '-_'; }

generate_env() {
  local host port
  host="$(detect_host)"
  port="${ONTRAK_LOCAL_AUTHENTIK_PORT:-9000}"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by deploy/authentik/setup.sh — local development only.
# Gitignored (.gitignore). Delete it to start over with fresh secrets.

# ── the local Authentik itself ──
AUTHENTIK_TAG=${ONTRAK_LOCAL_AUTHENTIK_TAG:-2026.8.3}
AUTHENTIK_HTTP_PORT=$port
AUTHENTIK_BIND_ADDR=${ONTRAK_LOCAL_AUTHENTIK_BIND:-0.0.0.0}
PG_PASS=$(rand 36)
AUTHENTIK_SECRET_KEY=$(rand 60)
# The admin account's password (UI) and API token (provisioning). akadmin.
AUTHENTIK_BOOTSTRAP_PASSWORD=$(rand 18)
AUTHENTIK_BOOTSTRAP_TOKEN=$(openssl rand -hex 32)

# ── where this range lives, and the callbacks it answers on ──
ONTRAK_LOCAL_HOST=$host
ONTRAK_LOCAL_OIDC_CLIENT_ID=ontrak
ONTRAK_LOCAL_OIDC_CLIENT_SECRET=$(openssl rand -hex 32)
ONTRAK_LOCAL_OIDC_REDIRECT_URI=http://localhost:8080/oidc/callback,http://127.0.0.1:8080/oidc/callback,http://$host:8080/oidc/callback

# ── the seed accounts provision.py creates ──
ONTRAK_LOCAL_INSTRUCTOR=instructor@ontrak.lab
ONTRAK_LOCAL_STUDENT_DOMAIN=ontrak.lab
ONTRAK_LOCAL_STUDENTS=6
ONTRAK_LOCAL_SEED_PASSWORD=$(rand 12)
EOF
  ok "wrote $ENV_FILE (fresh secrets)"
}

load_env() {
  [ -f "$ENV_FILE" ] || die "$ENV_FILE is missing — run this script without arguments first"
  set -a
  # shellcheck disable=SC1090  # a generated env file, by design
  . "$ENV_FILE"
  set +a
}


# ------------------------------------------------------------------- the stack --
compose() {
  docker compose --env-file "$ENV_FILE" -f "$HERE/compose.yaml" "$@"
}

wait_for_ready() {
  local port="$1" deadline=$((SECONDS + 300)) url
  for url in "http://127.0.0.1:$port/-/health/ready/" "http://127.0.0.1:$port/-/health/live/" "http://127.0.0.1:$port/"; do
    while [ "$SECONDS" -lt "$deadline" ]; do
      if curl -fsS -o /dev/null --max-time 4 "$url" 2>/dev/null; then
        ok "Authentik is answering at $url"
        return 0
      fi
      sleep 3
    done
  done
  return 1
}


# ------------------------------------------------------------------- provision --
provision() {
  # provision.py is stdlib-only, so the system interpreter runs it — but the
  # checkout's venv is used when there is one, because that is what `make setup`
  # left behind and it is the one the rest of the project's scripts use.
  local python="python3"
  if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
    python="$REPO_ROOT/.venv/bin/python"
  fi
  # Authentik is reached on loopback here: this script and the API call it makes
  # are both on the host. The *issuer URL* in ontrak-oidc.env is the host
  # address, because that one is for the browser and the portal container.
  AUTHENTIK_URL="http://127.0.0.1:${AUTHENTIK_HTTP_PORT}" "$python" "$HERE/provision.py"
}


# ------------------------------------------------------------------ the values --
# A compose *env file*, not a shell script to source: `docker compose --env-file`
# reads it while it is still resolving `${...}` in docker-compose.yml, which is
# the only place these can be set. A service's `env_file:` is read later and
# loses to the compose file's own `environment:` block, so it cannot override a
# declared variable — and the portal declares all of these.
write_local_env() {
  local issuer="http://${ONTRAK_LOCAL_HOST}:${AUTHENTIK_HTTP_PORT}/application/o/ontrak/"
  umask 077
  cat >"$LOCAL_ENV_FILE" <<EOF
# Generated by deploy/authentik/setup.sh — how a local range is pointed at the
# standalone Authentik in this directory. Gitignored: it holds a client secret.
#
# Use it by passing the checkout's .env first and this file second, so this one
# wins where the two disagree:
#
#   docker compose --env-file .env --env-file deploy/authentik/ontrak-local.env \\
#     up -d portal
#
# Or let setup.sh do exactly that: deploy/authentik/setup.sh --connect
#
# A bare 'docker compose up -d' resolves these from .env instead and puts the
# range back on the estate's Authentik — run --connect again to return to this
# one.
ONTRAK_PORTAL__OIDC_ISSUER=$issuer
ONTRAK_PORTAL__OIDC_CLIENT_ID=${ONTRAK_LOCAL_OIDC_CLIENT_ID}
ONTRAK_PORTAL__OIDC_CLIENT_SECRET=${ONTRAK_LOCAL_OIDC_CLIENT_SECRET}
ONTRAK_PORTAL__OIDC_REDIRECT_URI=${ONTRAK_LOCAL_OIDC_REDIRECT_URI}
ONTRAK_PORTAL__OIDC_INSTRUCTOR_GROUP=range-instructors

# The address a student's browser uses for this range and its console. The host
# address rather than localhost, for the reason at the top of this file: it is
# the one name the browser and the containers agree on.
ONTRAK_BIND_ADDR=${ONTRAK_LOCAL_BIND:-0.0.0.0}
ONTRAK_GUAC__BASE_URL=http://${ONTRAK_LOCAL_HOST}:${ONTRAK_PORTAL__PORT:-8080}/guacamole/

# A local range has no hypervisor-backed machines until the golden Windows image
# has been built ('make golden', 30-60 minutes) — so it serves its scenarios from
# demo mode, which is an in-memory Incus and a driver that reports plausible
# grades. That is what makes a class work end to end here. Set it to false once
# the image and the templates exist and the range should hand out real VMs.
ONTRAK_DEMO__ENABLED=${ONTRAK_LOCAL_DEMO:-true}
EOF
  ok "wrote $LOCAL_ENV_FILE"
}


# -------------------------------------------------------------------- connect --
# Two env files on one command line: the checkout's own first, so a range keeps
# every other setting it has, and the local one second, so it wins on the values
# they disagree about. The operator's .env is never written to — wiring a range
# to a local IdP is a thing you do to a running stack, and undoing it is running
# compose without the second file.
connect() {
  log "pointing the local OnTrak portal at this Authentik"
  local env_args=(--env-file "$LOCAL_ENV_FILE")
  if [ -f "$REPO_ROOT/.env" ]; then
    env_args=(--env-file .env "${env_args[@]}")
  fi
  # portal *and* gateway: the portal reads the issuer from its environment, but
  # the address students reach it on is the gateway's published port, and
  # ONTRAK_BIND_ADDR is read there. Recreating only the portal leaves a range
  # that signs in and cannot be reached.
  ( cd "$REPO_ROOT" && docker compose "${env_args[@]}" -f docker-compose.yml up -d portal gateway )
  ok "portal and gateway recreated against http://${ONTRAK_LOCAL_HOST}:${AUTHENTIK_HTTP_PORT}"
}


# ------------------------------------------------------------------------ run --
case "${1:-}" in
  --down | down)
    load_env
    log "stopping the local Authentik (its database is kept)"
    compose down
    exit 0
    ;;
  --help | -h)
    sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
esac

if [ ! -f "$ENV_FILE" ]; then
  generate_env
else
  ok "using the existing $ENV_FILE (delete it for fresh secrets)"
fi

load_env

log "starting Authentik (${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG}) on port ${AUTHENTIK_HTTP_PORT}"
compose up -d

if ! wait_for_ready "$AUTHENTIK_HTTP_PORT"; then
  warn "Authentik did not report ready in time; recent logs:"
  compose logs --tail 40 server || true
  die "giving up — check 'docker compose -f $HERE/compose.yaml logs'"
fi

log "provisioning OnTrak's application, groups and accounts"
provision

write_local_env

cat <<EOF

$(log "local Authentik ready")

  admin UI     http://${ONTRAK_LOCAL_HOST}:${AUTHENTIK_HTTP_PORT}/
               sign in as akadmin / ${AUTHENTIK_BOOTSTRAP_PASSWORD}

  issuer       http://${ONTRAK_LOCAL_HOST}:${AUTHENTIK_HTTP_PORT}/application/o/ontrak/
  accounts     ${ONTRAK_LOCAL_INSTRUCTOR}  (instructor)
               student1..${ONTRAK_LOCAL_STUDENTS}@${ONTRAK_LOCAL_STUDENT_DOMAIN}   (students)
               password for all of them: ${ONTRAK_LOCAL_SEED_PASSWORD}

Next:
  1. point the range at it:   deploy/authentik/setup.sh --connect
  2. open the portal and use "Sign in with Authentik"
EOF

if [ "${1:-}" = "--connect" ]; then
  connect
fi
